networks:
  soc-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/24

volumes:
  soc-logs:
  esdata:
    external: true
    name: soc-project_esdata

services:

  model-server:
    build: ./model-server
    container_name: ids-model-server
    ports:
      - "8000:8000"
    networks:
      soc-network:
        ipv4_address: 172.25.0.2
    restart: unless-stopped

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      soc-network:
        ipv4_address: 172.25.0.5
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s
    restart: unless-stopped

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.0
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      soc-network:
        ipv4_address: 172.25.0.6
    restart: unless-stopped
